// Code generated by ent, DO NOT EDIT.

package adminrolepermission

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the adminrolepermission type in the database.
	Label = "admin_role_permission"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAdminRoleID holds the string denoting the admin_role_id field in the database.
	FieldAdminRoleID = "admin_role_id"
	// FieldAdminPermissionID holds the string denoting the admin_permission_id field in the database.
	FieldAdminPermissionID = "admin_permission_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the adminrolepermission in the database.
	Table = "admin_role_permissions"
)

// Columns holds all SQL columns for adminrolepermission fields.
var Columns = []string{
	FieldID,
	FieldAdminRoleID,
	FieldAdminPermissionID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the AdminRolePermission queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAdminRoleID orders the results by the admin_role_id field.
func ByAdminRoleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminRoleID, opts...).ToFunc()
}

// ByAdminPermissionID orders the results by the admin_permission_id field.
func ByAdminPermissionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminPermissionID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
