// Code generated by ent, DO NOT EDIT.

package adminrolepermission

import (
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldLTE(FieldID, id))
}

// AdminRoleID applies equality check predicate on the "admin_role_id" field. It's identical to AdminRoleIDEQ.
func AdminRoleID(v int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldEQ(FieldAdminRoleID, v))
}

// AdminPermissionID applies equality check predicate on the "admin_permission_id" field. It's identical to AdminPermissionIDEQ.
func AdminPermissionID(v int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldEQ(FieldAdminPermissionID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldEQ(FieldCreatedAt, v))
}

// AdminRoleIDEQ applies the EQ predicate on the "admin_role_id" field.
func AdminRoleIDEQ(v int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldEQ(FieldAdminRoleID, v))
}

// AdminRoleIDNEQ applies the NEQ predicate on the "admin_role_id" field.
func AdminRoleIDNEQ(v int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldNEQ(FieldAdminRoleID, v))
}

// AdminRoleIDIn applies the In predicate on the "admin_role_id" field.
func AdminRoleIDIn(vs ...int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldIn(FieldAdminRoleID, vs...))
}

// AdminRoleIDNotIn applies the NotIn predicate on the "admin_role_id" field.
func AdminRoleIDNotIn(vs ...int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldNotIn(FieldAdminRoleID, vs...))
}

// AdminRoleIDGT applies the GT predicate on the "admin_role_id" field.
func AdminRoleIDGT(v int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldGT(FieldAdminRoleID, v))
}

// AdminRoleIDGTE applies the GTE predicate on the "admin_role_id" field.
func AdminRoleIDGTE(v int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldGTE(FieldAdminRoleID, v))
}

// AdminRoleIDLT applies the LT predicate on the "admin_role_id" field.
func AdminRoleIDLT(v int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldLT(FieldAdminRoleID, v))
}

// AdminRoleIDLTE applies the LTE predicate on the "admin_role_id" field.
func AdminRoleIDLTE(v int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldLTE(FieldAdminRoleID, v))
}

// AdminPermissionIDEQ applies the EQ predicate on the "admin_permission_id" field.
func AdminPermissionIDEQ(v int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldEQ(FieldAdminPermissionID, v))
}

// AdminPermissionIDNEQ applies the NEQ predicate on the "admin_permission_id" field.
func AdminPermissionIDNEQ(v int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldNEQ(FieldAdminPermissionID, v))
}

// AdminPermissionIDIn applies the In predicate on the "admin_permission_id" field.
func AdminPermissionIDIn(vs ...int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldIn(FieldAdminPermissionID, vs...))
}

// AdminPermissionIDNotIn applies the NotIn predicate on the "admin_permission_id" field.
func AdminPermissionIDNotIn(vs ...int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldNotIn(FieldAdminPermissionID, vs...))
}

// AdminPermissionIDGT applies the GT predicate on the "admin_permission_id" field.
func AdminPermissionIDGT(v int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldGT(FieldAdminPermissionID, v))
}

// AdminPermissionIDGTE applies the GTE predicate on the "admin_permission_id" field.
func AdminPermissionIDGTE(v int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldGTE(FieldAdminPermissionID, v))
}

// AdminPermissionIDLT applies the LT predicate on the "admin_permission_id" field.
func AdminPermissionIDLT(v int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldLT(FieldAdminPermissionID, v))
}

// AdminPermissionIDLTE applies the LTE predicate on the "admin_permission_id" field.
func AdminPermissionIDLTE(v int) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldLTE(FieldAdminPermissionID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdminRolePermission) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdminRolePermission) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdminRolePermission) predicate.AdminRolePermission {
	return predicate.AdminRolePermission(sql.NotPredicates(p))
}
