cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

hubble:
  relay:
    enabled: true
  ui:
    enabled: true

ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.244.0.0/16

k8sServiceHost: 192.168.0.110
k8sServicePort: 6443
# kube-proxy replacement 需要稳定访问 API VIP；当前 kubeadm + kube-vip 的入口就是 192.168.0.110:6443。
# 这里显式开启，收口 ClusterIP / NodePort / LoadBalancer 转发到 Cilium eBPF datapath。
kubeProxyReplacement: true

operator:
  replicas: 1
