apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: app-pg-lab
  namespace: database
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - database
  selector:
    matchLabels:
      cnpg.io/cluster: app-pg
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
