apiVersion: v1
kind: ConfigMap
metadata:
  name: lab-ha-grafana-loki-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    release: kube-prometheus-stack
data:
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://loki.logging:3100/
        jsonData:
          maxLines: 2000
