defaultSettings:
  autoDeletePodWhenVolumeDetachedUnexpectedly: true
  autoSalvage: true
  createDefaultDiskLabeledNodes: false
  defaultDataPath: /var/lib/longhorn
  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod

global:
  cattle:
    systemDefaultRegistry: docker.m.daocloud.io

persistence:
  defaultClassReplicaCount: 2
