image:
  registry: docker.m.daocloud.io
  repository: bitnami/sealed-secrets-controller
  tag: 0.36.1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

serviceMonitor:
  enabled: true
  additionalLabels:
    release: kube-prometheus-stack
