-- Create "admin_permissions" table
CREATE TABLE "admin_permissions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "key" character varying NOT NULL,
  "name" character varying NOT NULL,
  "group" character varying NULL DEFAULT '',
  "description" character varying NULL DEFAULT '',
  "builtin" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "adminpermission_key" to table: "admin_permissions"
CREATE UNIQUE INDEX "adminpermission_key" ON "admin_permissions" ("key");
-- Create "admin_role_permissions" table
CREATE TABLE "admin_role_permissions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "admin_role_id" bigint NOT NULL,
  "admin_permission_id" bigint NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "adminrolepermission_admin_permission_id" to table: "admin_role_permissions"
CREATE INDEX "adminrolepermission_admin_permission_id" ON "admin_role_permissions" ("admin_permission_id");
-- Create index "adminrolepermission_admin_role_id_admin_permission_id" to table: "admin_role_permissions"
CREATE UNIQUE INDEX "adminrolepermission_admin_role_id_admin_permission_id" ON "admin_role_permissions" ("admin_role_id", "admin_permission_id");
-- Create "admin_roles" table
CREATE TABLE "admin_roles" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "key" character varying NOT NULL,
  "name" character varying NOT NULL,
  "description" character varying NULL DEFAULT '',
  "builtin" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "adminrole_key" to table: "admin_roles"
CREATE UNIQUE INDEX "adminrole_key" ON "admin_roles" ("key");
-- Create "admin_user_roles" table
CREATE TABLE "admin_user_roles" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "admin_user_id" bigint NOT NULL,
  "admin_role_id" bigint NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "adminuserrole_admin_role_id" to table: "admin_user_roles"
CREATE INDEX "adminuserrole_admin_role_id" ON "admin_user_roles" ("admin_role_id");
-- Create index "adminuserrole_admin_user_id_admin_role_id" to table: "admin_user_roles"
CREATE UNIQUE INDEX "adminuserrole_admin_user_id_admin_role_id" ON "admin_user_roles" ("admin_user_id", "admin_role_id");
