-- Create "admin_users" table
CREATE TABLE "admin_users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "username" character varying NOT NULL,
  "password_hash" character varying NOT NULL,
  "disabled" boolean NOT NULL DEFAULT false,
  "last_login_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "adminuser_username" to table: "admin_users"
CREATE UNIQUE INDEX "adminuser_username" ON "admin_users" ("username");
-- Create "users" table
CREATE TABLE "users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "username" character varying NOT NULL,
  "password_hash" character varying NOT NULL,
  "disabled" boolean NOT NULL DEFAULT false,
  "last_login_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "user_username" to table: "users"
CREATE UNIQUE INDEX "user_username" ON "users" ("username");
