// 统一维护前端消费到的错误码，避免各页面散落魔法数字后语义漂移。
export const RpcErrorCode = Object.freeze({
  OK: 0,
  JSONRPC_UNKNOWN_URL: 40001,
  INVALID_PARAM: 40010,
  ADMIN_INVALID_LEVEL: 40011,
  ADMIN_INVALID_PARENT: 40012,
  UNKNOWN_METHOD: 40020,
  USER_INVALID_PARAM: 40030,
  USER_POINTS_SET_INVALID: 40061,
  USER_POINTS_ADD_INVALID: 40062,
  USER_EXPIRES_SET_INVALID: 40063,
  USER_EXPIRES_EXTEND_INVALID_USER: 40064,
  USER_EXPIRES_EXTEND_INVALID_DELTA: 40065,
  USER_SET_DISABLED_INVALID: 40071,
  SUBSCRIPTION_INVALID_USER: 40080,
  SUBSCRIPTION_INVALID_CODE: 40081,
  SUBSCRIPTION_INVALID_DAYS: 40082,
  SUBSCRIPTION_DAYS_TOO_LARGE: 40083,
  SUBSCRIPTION_UNKNOWN_METHOD: 40084,
  ADMIN_REQUIRED: 40301,
  AUTH_REQUIRED: 40302,
  ADMIN_DISABLED: 40303,
  PERMISSION_DENIED: 40304,
  ADMIN_NOT_FOUND: 40410,
  ADMIN_EXISTS: 40910,
  AUTH_USER_NOT_FOUND: 10001,
  AUTH_INVALID_PASSWORD: 10002,
  AUTH_USER_DISABLED: 10003,
  AUTH_USER_EXISTS: 10004,
  AUTH_EXPIRED: 10005,
  AUTH_INVALID: 10006,
  INTERNAL: 50000,
  AUTH_CURRENT_USER_FAILED: 50001,
  USER_LIST_FAILED: 50020,
})

export const AUTH_FAILURE_ERROR_CODES = Object.freeze([
  RpcErrorCode.AUTH_EXPIRED,
  RpcErrorCode.AUTH_INVALID,
  RpcErrorCode.AUTH_REQUIRED,
])

// 仅登录态失效错误会触发登出，权限不足必须保留当前会话。
export function isAuthFailureCode(code) {
  return AUTH_FAILURE_ERROR_CODES.includes(Number(code))
}

export const DEFAULT_RPC_ERROR_MESSAGES = Object.freeze({
  [RpcErrorCode.ADMIN_REQUIRED]: '只有管理员才能操作',
  [RpcErrorCode.AUTH_REQUIRED]: '请先登录',
  [RpcErrorCode.ADMIN_DISABLED]: '管理员已禁用',
  [RpcErrorCode.PERMISSION_DENIED]: '权限不足',
  [RpcErrorCode.AUTH_USER_NOT_FOUND]: '用户不存在',
  [RpcErrorCode.AUTH_INVALID_PASSWORD]: '密码错误',
  [RpcErrorCode.AUTH_USER_DISABLED]: '用户已被禁用',
  [RpcErrorCode.AUTH_USER_EXISTS]: '用户名已存在',
  [RpcErrorCode.AUTH_EXPIRED]: '登录已过期，请重新登录',
  [RpcErrorCode.AUTH_INVALID]: '登录无效，请重新登录',
})
