# yamllint disable-file
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ required "ingress.name is required" .Values.ingress.name }}
  namespace: {{ required "namespace.name is required" .Values.namespace.name }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    {{- range .Values.ingress.rules }}
    - {{- if .host }} host: {{ .host }}{{ end }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ default $.Values.service.name .serviceName }}
                port:
                  number: {{ .servicePort }}
          {{- end }}
    {{- end }}
{{- end }}
