# yamllint disable-file
{{- if .Values.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ required "limitRange.name is required" .Values.limitRange.name }}
  namespace: {{ required "namespace.name is required" .Values.namespace.name }}
spec:
  limits:
{{ toYaml .Values.limitRange.limits | nindent 4 }}
{{- end }}
