# yamllint disable-file
{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ required "namespace.name is required" .Values.namespace.name }}
  labels:
{{ toYaml .Values.namespace.labels | nindent 4 }}
{{- end }}
