// Code generated by ent, DO NOT EDIT.

package adminuserrole

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the adminuserrole type in the database.
	Label = "admin_user_role"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAdminUserID holds the string denoting the admin_user_id field in the database.
	FieldAdminUserID = "admin_user_id"
	// FieldAdminRoleID holds the string denoting the admin_role_id field in the database.
	FieldAdminRoleID = "admin_role_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the adminuserrole in the database.
	Table = "admin_user_roles"
)

// Columns holds all SQL columns for adminuserrole fields.
var Columns = []string{
	FieldID,
	FieldAdminUserID,
	FieldAdminRoleID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the AdminUserRole queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAdminUserID orders the results by the admin_user_id field.
func ByAdminUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminUserID, opts...).ToFunc()
}

// ByAdminRoleID orders the results by the admin_role_id field.
func ByAdminRoleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminRoleID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
