// Code generated by ent, DO NOT EDIT.

package adminuserrole

import (
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldLTE(FieldID, id))
}

// AdminUserID applies equality check predicate on the "admin_user_id" field. It's identical to AdminUserIDEQ.
func AdminUserID(v int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldEQ(FieldAdminUserID, v))
}

// AdminRoleID applies equality check predicate on the "admin_role_id" field. It's identical to AdminRoleIDEQ.
func AdminRoleID(v int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldEQ(FieldAdminRoleID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldEQ(FieldCreatedAt, v))
}

// AdminUserIDEQ applies the EQ predicate on the "admin_user_id" field.
func AdminUserIDEQ(v int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldEQ(FieldAdminUserID, v))
}

// AdminUserIDNEQ applies the NEQ predicate on the "admin_user_id" field.
func AdminUserIDNEQ(v int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldNEQ(FieldAdminUserID, v))
}

// AdminUserIDIn applies the In predicate on the "admin_user_id" field.
func AdminUserIDIn(vs ...int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldIn(FieldAdminUserID, vs...))
}

// AdminUserIDNotIn applies the NotIn predicate on the "admin_user_id" field.
func AdminUserIDNotIn(vs ...int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldNotIn(FieldAdminUserID, vs...))
}

// AdminUserIDGT applies the GT predicate on the "admin_user_id" field.
func AdminUserIDGT(v int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldGT(FieldAdminUserID, v))
}

// AdminUserIDGTE applies the GTE predicate on the "admin_user_id" field.
func AdminUserIDGTE(v int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldGTE(FieldAdminUserID, v))
}

// AdminUserIDLT applies the LT predicate on the "admin_user_id" field.
func AdminUserIDLT(v int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldLT(FieldAdminUserID, v))
}

// AdminUserIDLTE applies the LTE predicate on the "admin_user_id" field.
func AdminUserIDLTE(v int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldLTE(FieldAdminUserID, v))
}

// AdminRoleIDEQ applies the EQ predicate on the "admin_role_id" field.
func AdminRoleIDEQ(v int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldEQ(FieldAdminRoleID, v))
}

// AdminRoleIDNEQ applies the NEQ predicate on the "admin_role_id" field.
func AdminRoleIDNEQ(v int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldNEQ(FieldAdminRoleID, v))
}

// AdminRoleIDIn applies the In predicate on the "admin_role_id" field.
func AdminRoleIDIn(vs ...int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldIn(FieldAdminRoleID, vs...))
}

// AdminRoleIDNotIn applies the NotIn predicate on the "admin_role_id" field.
func AdminRoleIDNotIn(vs ...int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldNotIn(FieldAdminRoleID, vs...))
}

// AdminRoleIDGT applies the GT predicate on the "admin_role_id" field.
func AdminRoleIDGT(v int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldGT(FieldAdminRoleID, v))
}

// AdminRoleIDGTE applies the GTE predicate on the "admin_role_id" field.
func AdminRoleIDGTE(v int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldGTE(FieldAdminRoleID, v))
}

// AdminRoleIDLT applies the LT predicate on the "admin_role_id" field.
func AdminRoleIDLT(v int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldLT(FieldAdminRoleID, v))
}

// AdminRoleIDLTE applies the LTE predicate on the "admin_role_id" field.
func AdminRoleIDLTE(v int) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldLTE(FieldAdminRoleID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdminUserRole) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdminUserRole) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdminUserRole) predicate.AdminUserRole {
	return predicate.AdminUserRole(sql.NotPredicates(p))
}
