// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/adminpermission"
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdminPermissionUpdate is the builder for updating AdminPermission entities.
type AdminPermissionUpdate struct {
	config
	hooks    []Hook
	mutation *AdminPermissionMutation
}

// Where appends a list predicates to the AdminPermissionUpdate builder.
func (_u *AdminPermissionUpdate) Where(ps ...predicate.AdminPermission) *AdminPermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *AdminPermissionUpdate) SetKey(v string) *AdminPermissionUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *AdminPermissionUpdate) SetNillableKey(v *string) *AdminPermissionUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AdminPermissionUpdate) SetName(v string) *AdminPermissionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AdminPermissionUpdate) SetNillableName(v *string) *AdminPermissionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGroup sets the "group" field.
func (_u *AdminPermissionUpdate) SetGroup(v string) *AdminPermissionUpdate {
	_u.mutation.SetGroup(v)
	return _u
}

// SetNillableGroup sets the "group" field if the given value is not nil.
func (_u *AdminPermissionUpdate) SetNillableGroup(v *string) *AdminPermissionUpdate {
	if v != nil {
		_u.SetGroup(*v)
	}
	return _u
}

// ClearGroup clears the value of the "group" field.
func (_u *AdminPermissionUpdate) ClearGroup() *AdminPermissionUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// SetDescription sets the "description" field.
func (_u *AdminPermissionUpdate) SetDescription(v string) *AdminPermissionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AdminPermissionUpdate) SetNillableDescription(v *string) *AdminPermissionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AdminPermissionUpdate) ClearDescription() *AdminPermissionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetBuiltin sets the "builtin" field.
func (_u *AdminPermissionUpdate) SetBuiltin(v bool) *AdminPermissionUpdate {
	_u.mutation.SetBuiltin(v)
	return _u
}

// SetNillableBuiltin sets the "builtin" field if the given value is not nil.
func (_u *AdminPermissionUpdate) SetNillableBuiltin(v *bool) *AdminPermissionUpdate {
	if v != nil {
		_u.SetBuiltin(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminPermissionUpdate) SetUpdatedAt(v time.Time) *AdminPermissionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AdminPermissionMutation object of the builder.
func (_u *AdminPermissionUpdate) Mutation() *AdminPermissionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminPermissionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminPermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminPermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminPermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminPermissionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adminpermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminPermissionUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := adminpermission.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "AdminPermission.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := adminpermission.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AdminPermission.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Group(); ok {
		if err := adminpermission.GroupValidator(v); err != nil {
			return &ValidationError{Name: "group", err: fmt.Errorf(`ent: validator failed for field "AdminPermission.group": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := adminpermission.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "AdminPermission.description": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminPermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminpermission.Table, adminpermission.Columns, sqlgraph.NewFieldSpec(adminpermission.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(adminpermission.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(adminpermission.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Group(); ok {
		_spec.SetField(adminpermission.FieldGroup, field.TypeString, value)
	}
	if _u.mutation.GroupCleared() {
		_spec.ClearField(adminpermission.FieldGroup, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(adminpermission.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(adminpermission.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Builtin(); ok {
		_spec.SetField(adminpermission.FieldBuiltin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminpermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminpermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminPermissionUpdateOne is the builder for updating a single AdminPermission entity.
type AdminPermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminPermissionMutation
}

// SetKey sets the "key" field.
func (_u *AdminPermissionUpdateOne) SetKey(v string) *AdminPermissionUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *AdminPermissionUpdateOne) SetNillableKey(v *string) *AdminPermissionUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AdminPermissionUpdateOne) SetName(v string) *AdminPermissionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AdminPermissionUpdateOne) SetNillableName(v *string) *AdminPermissionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGroup sets the "group" field.
func (_u *AdminPermissionUpdateOne) SetGroup(v string) *AdminPermissionUpdateOne {
	_u.mutation.SetGroup(v)
	return _u
}

// SetNillableGroup sets the "group" field if the given value is not nil.
func (_u *AdminPermissionUpdateOne) SetNillableGroup(v *string) *AdminPermissionUpdateOne {
	if v != nil {
		_u.SetGroup(*v)
	}
	return _u
}

// ClearGroup clears the value of the "group" field.
func (_u *AdminPermissionUpdateOne) ClearGroup() *AdminPermissionUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// SetDescription sets the "description" field.
func (_u *AdminPermissionUpdateOne) SetDescription(v string) *AdminPermissionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AdminPermissionUpdateOne) SetNillableDescription(v *string) *AdminPermissionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AdminPermissionUpdateOne) ClearDescription() *AdminPermissionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetBuiltin sets the "builtin" field.
func (_u *AdminPermissionUpdateOne) SetBuiltin(v bool) *AdminPermissionUpdateOne {
	_u.mutation.SetBuiltin(v)
	return _u
}

// SetNillableBuiltin sets the "builtin" field if the given value is not nil.
func (_u *AdminPermissionUpdateOne) SetNillableBuiltin(v *bool) *AdminPermissionUpdateOne {
	if v != nil {
		_u.SetBuiltin(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminPermissionUpdateOne) SetUpdatedAt(v time.Time) *AdminPermissionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AdminPermissionMutation object of the builder.
func (_u *AdminPermissionUpdateOne) Mutation() *AdminPermissionMutation {
	return _u.mutation
}

// Where appends a list predicates to the AdminPermissionUpdate builder.
func (_u *AdminPermissionUpdateOne) Where(ps ...predicate.AdminPermission) *AdminPermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminPermissionUpdateOne) Select(field string, fields ...string) *AdminPermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminPermission entity.
func (_u *AdminPermissionUpdateOne) Save(ctx context.Context) (*AdminPermission, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminPermissionUpdateOne) SaveX(ctx context.Context) *AdminPermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminPermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminPermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminPermissionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adminpermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminPermissionUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := adminpermission.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "AdminPermission.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := adminpermission.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AdminPermission.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Group(); ok {
		if err := adminpermission.GroupValidator(v); err != nil {
			return &ValidationError{Name: "group", err: fmt.Errorf(`ent: validator failed for field "AdminPermission.group": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := adminpermission.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "AdminPermission.description": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminPermissionUpdateOne) sqlSave(ctx context.Context) (_node *AdminPermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminpermission.Table, adminpermission.Columns, sqlgraph.NewFieldSpec(adminpermission.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminPermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminpermission.FieldID)
		for _, f := range fields {
			if !adminpermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminpermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(adminpermission.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(adminpermission.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Group(); ok {
		_spec.SetField(adminpermission.FieldGroup, field.TypeString, value)
	}
	if _u.mutation.GroupCleared() {
		_spec.ClearField(adminpermission.FieldGroup, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(adminpermission.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(adminpermission.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Builtin(); ok {
		_spec.SetField(adminpermission.FieldBuiltin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminpermission.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AdminPermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminpermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
