// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/adminuserrole"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdminUserRoleCreate is the builder for creating a AdminUserRole entity.
type AdminUserRoleCreate struct {
	config
	mutation *AdminUserRoleMutation
	hooks    []Hook
}

// SetAdminUserID sets the "admin_user_id" field.
func (_c *AdminUserRoleCreate) SetAdminUserID(v int) *AdminUserRoleCreate {
	_c.mutation.SetAdminUserID(v)
	return _c
}

// SetAdminRoleID sets the "admin_role_id" field.
func (_c *AdminUserRoleCreate) SetAdminRoleID(v int) *AdminUserRoleCreate {
	_c.mutation.SetAdminRoleID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdminUserRoleCreate) SetCreatedAt(v time.Time) *AdminUserRoleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdminUserRoleCreate) SetNillableCreatedAt(v *time.Time) *AdminUserRoleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the AdminUserRoleMutation object of the builder.
func (_c *AdminUserRoleCreate) Mutation() *AdminUserRoleMutation {
	return _c.mutation
}

// Save creates the AdminUserRole in the database.
func (_c *AdminUserRoleCreate) Save(ctx context.Context) (*AdminUserRole, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdminUserRoleCreate) SaveX(ctx context.Context) *AdminUserRole {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminUserRoleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminUserRoleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdminUserRoleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := adminuserrole.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdminUserRoleCreate) check() error {
	if _, ok := _c.mutation.AdminUserID(); !ok {
		return &ValidationError{Name: "admin_user_id", err: errors.New(`ent: missing required field "AdminUserRole.admin_user_id"`)}
	}
	if _, ok := _c.mutation.AdminRoleID(); !ok {
		return &ValidationError{Name: "admin_role_id", err: errors.New(`ent: missing required field "AdminUserRole.admin_role_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AdminUserRole.created_at"`)}
	}
	return nil
}

func (_c *AdminUserRoleCreate) sqlSave(ctx context.Context) (*AdminUserRole, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdminUserRoleCreate) createSpec() (*AdminUserRole, *sqlgraph.CreateSpec) {
	var (
		_node = &AdminUserRole{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adminuserrole.Table, sqlgraph.NewFieldSpec(adminuserrole.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.AdminUserID(); ok {
		_spec.SetField(adminuserrole.FieldAdminUserID, field.TypeInt, value)
		_node.AdminUserID = value
	}
	if value, ok := _c.mutation.AdminRoleID(); ok {
		_spec.SetField(adminuserrole.FieldAdminRoleID, field.TypeInt, value)
		_node.AdminRoleID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(adminuserrole.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// AdminUserRoleCreateBulk is the builder for creating many AdminUserRole entities in bulk.
type AdminUserRoleCreateBulk struct {
	config
	err      error
	builders []*AdminUserRoleCreate
}

// Save creates the AdminUserRole entities in the database.
func (_c *AdminUserRoleCreateBulk) Save(ctx context.Context) ([]*AdminUserRole, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AdminUserRole, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdminUserRoleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdminUserRoleCreateBulk) SaveX(ctx context.Context) []*AdminUserRole {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminUserRoleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminUserRoleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
