// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/adminrolepermission"
	"server/internal/data/model/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdminRolePermissionUpdate is the builder for updating AdminRolePermission entities.
type AdminRolePermissionUpdate struct {
	config
	hooks    []Hook
	mutation *AdminRolePermissionMutation
}

// Where appends a list predicates to the AdminRolePermissionUpdate builder.
func (_u *AdminRolePermissionUpdate) Where(ps ...predicate.AdminRolePermission) *AdminRolePermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAdminRoleID sets the "admin_role_id" field.
func (_u *AdminRolePermissionUpdate) SetAdminRoleID(v int) *AdminRolePermissionUpdate {
	_u.mutation.ResetAdminRoleID()
	_u.mutation.SetAdminRoleID(v)
	return _u
}

// SetNillableAdminRoleID sets the "admin_role_id" field if the given value is not nil.
func (_u *AdminRolePermissionUpdate) SetNillableAdminRoleID(v *int) *AdminRolePermissionUpdate {
	if v != nil {
		_u.SetAdminRoleID(*v)
	}
	return _u
}

// AddAdminRoleID adds value to the "admin_role_id" field.
func (_u *AdminRolePermissionUpdate) AddAdminRoleID(v int) *AdminRolePermissionUpdate {
	_u.mutation.AddAdminRoleID(v)
	return _u
}

// SetAdminPermissionID sets the "admin_permission_id" field.
func (_u *AdminRolePermissionUpdate) SetAdminPermissionID(v int) *AdminRolePermissionUpdate {
	_u.mutation.ResetAdminPermissionID()
	_u.mutation.SetAdminPermissionID(v)
	return _u
}

// SetNillableAdminPermissionID sets the "admin_permission_id" field if the given value is not nil.
func (_u *AdminRolePermissionUpdate) SetNillableAdminPermissionID(v *int) *AdminRolePermissionUpdate {
	if v != nil {
		_u.SetAdminPermissionID(*v)
	}
	return _u
}

// AddAdminPermissionID adds value to the "admin_permission_id" field.
func (_u *AdminRolePermissionUpdate) AddAdminPermissionID(v int) *AdminRolePermissionUpdate {
	_u.mutation.AddAdminPermissionID(v)
	return _u
}

// Mutation returns the AdminRolePermissionMutation object of the builder.
func (_u *AdminRolePermissionUpdate) Mutation() *AdminRolePermissionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminRolePermissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminRolePermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminRolePermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminRolePermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AdminRolePermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(adminrolepermission.Table, adminrolepermission.Columns, sqlgraph.NewFieldSpec(adminrolepermission.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AdminRoleID(); ok {
		_spec.SetField(adminrolepermission.FieldAdminRoleID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdminRoleID(); ok {
		_spec.AddField(adminrolepermission.FieldAdminRoleID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AdminPermissionID(); ok {
		_spec.SetField(adminrolepermission.FieldAdminPermissionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdminPermissionID(); ok {
		_spec.AddField(adminrolepermission.FieldAdminPermissionID, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminrolepermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminRolePermissionUpdateOne is the builder for updating a single AdminRolePermission entity.
type AdminRolePermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminRolePermissionMutation
}

// SetAdminRoleID sets the "admin_role_id" field.
func (_u *AdminRolePermissionUpdateOne) SetAdminRoleID(v int) *AdminRolePermissionUpdateOne {
	_u.mutation.ResetAdminRoleID()
	_u.mutation.SetAdminRoleID(v)
	return _u
}

// SetNillableAdminRoleID sets the "admin_role_id" field if the given value is not nil.
func (_u *AdminRolePermissionUpdateOne) SetNillableAdminRoleID(v *int) *AdminRolePermissionUpdateOne {
	if v != nil {
		_u.SetAdminRoleID(*v)
	}
	return _u
}

// AddAdminRoleID adds value to the "admin_role_id" field.
func (_u *AdminRolePermissionUpdateOne) AddAdminRoleID(v int) *AdminRolePermissionUpdateOne {
	_u.mutation.AddAdminRoleID(v)
	return _u
}

// SetAdminPermissionID sets the "admin_permission_id" field.
func (_u *AdminRolePermissionUpdateOne) SetAdminPermissionID(v int) *AdminRolePermissionUpdateOne {
	_u.mutation.ResetAdminPermissionID()
	_u.mutation.SetAdminPermissionID(v)
	return _u
}

// SetNillableAdminPermissionID sets the "admin_permission_id" field if the given value is not nil.
func (_u *AdminRolePermissionUpdateOne) SetNillableAdminPermissionID(v *int) *AdminRolePermissionUpdateOne {
	if v != nil {
		_u.SetAdminPermissionID(*v)
	}
	return _u
}

// AddAdminPermissionID adds value to the "admin_permission_id" field.
func (_u *AdminRolePermissionUpdateOne) AddAdminPermissionID(v int) *AdminRolePermissionUpdateOne {
	_u.mutation.AddAdminPermissionID(v)
	return _u
}

// Mutation returns the AdminRolePermissionMutation object of the builder.
func (_u *AdminRolePermissionUpdateOne) Mutation() *AdminRolePermissionMutation {
	return _u.mutation
}

// Where appends a list predicates to the AdminRolePermissionUpdate builder.
func (_u *AdminRolePermissionUpdateOne) Where(ps ...predicate.AdminRolePermission) *AdminRolePermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminRolePermissionUpdateOne) Select(field string, fields ...string) *AdminRolePermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminRolePermission entity.
func (_u *AdminRolePermissionUpdateOne) Save(ctx context.Context) (*AdminRolePermission, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminRolePermissionUpdateOne) SaveX(ctx context.Context) *AdminRolePermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminRolePermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminRolePermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AdminRolePermissionUpdateOne) sqlSave(ctx context.Context) (_node *AdminRolePermission, err error) {
	_spec := sqlgraph.NewUpdateSpec(adminrolepermission.Table, adminrolepermission.Columns, sqlgraph.NewFieldSpec(adminrolepermission.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminRolePermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminrolepermission.FieldID)
		for _, f := range fields {
			if !adminrolepermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminrolepermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AdminRoleID(); ok {
		_spec.SetField(adminrolepermission.FieldAdminRoleID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdminRoleID(); ok {
		_spec.AddField(adminrolepermission.FieldAdminRoleID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AdminPermissionID(); ok {
		_spec.SetField(adminrolepermission.FieldAdminPermissionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdminPermissionID(); ok {
		_spec.AddField(adminrolepermission.FieldAdminPermissionID, field.TypeInt, value)
	}
	_node = &AdminRolePermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminrolepermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
