// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/adminrole"
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdminRoleUpdate is the builder for updating AdminRole entities.
type AdminRoleUpdate struct {
	config
	hooks    []Hook
	mutation *AdminRoleMutation
}

// Where appends a list predicates to the AdminRoleUpdate builder.
func (_u *AdminRoleUpdate) Where(ps ...predicate.AdminRole) *AdminRoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *AdminRoleUpdate) SetKey(v string) *AdminRoleUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *AdminRoleUpdate) SetNillableKey(v *string) *AdminRoleUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AdminRoleUpdate) SetName(v string) *AdminRoleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AdminRoleUpdate) SetNillableName(v *string) *AdminRoleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AdminRoleUpdate) SetDescription(v string) *AdminRoleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AdminRoleUpdate) SetNillableDescription(v *string) *AdminRoleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AdminRoleUpdate) ClearDescription() *AdminRoleUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetBuiltin sets the "builtin" field.
func (_u *AdminRoleUpdate) SetBuiltin(v bool) *AdminRoleUpdate {
	_u.mutation.SetBuiltin(v)
	return _u
}

// SetNillableBuiltin sets the "builtin" field if the given value is not nil.
func (_u *AdminRoleUpdate) SetNillableBuiltin(v *bool) *AdminRoleUpdate {
	if v != nil {
		_u.SetBuiltin(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminRoleUpdate) SetUpdatedAt(v time.Time) *AdminRoleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AdminRoleMutation object of the builder.
func (_u *AdminRoleUpdate) Mutation() *AdminRoleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminRoleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminRoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminRoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminRoleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adminrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminRoleUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := adminrole.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "AdminRole.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := adminrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AdminRole.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := adminrole.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "AdminRole.description": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminRoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminrole.Table, adminrole.Columns, sqlgraph.NewFieldSpec(adminrole.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(adminrole.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(adminrole.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(adminrole.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(adminrole.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Builtin(); ok {
		_spec.SetField(adminrole.FieldBuiltin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminRoleUpdateOne is the builder for updating a single AdminRole entity.
type AdminRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminRoleMutation
}

// SetKey sets the "key" field.
func (_u *AdminRoleUpdateOne) SetKey(v string) *AdminRoleUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *AdminRoleUpdateOne) SetNillableKey(v *string) *AdminRoleUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AdminRoleUpdateOne) SetName(v string) *AdminRoleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AdminRoleUpdateOne) SetNillableName(v *string) *AdminRoleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AdminRoleUpdateOne) SetDescription(v string) *AdminRoleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AdminRoleUpdateOne) SetNillableDescription(v *string) *AdminRoleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AdminRoleUpdateOne) ClearDescription() *AdminRoleUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetBuiltin sets the "builtin" field.
func (_u *AdminRoleUpdateOne) SetBuiltin(v bool) *AdminRoleUpdateOne {
	_u.mutation.SetBuiltin(v)
	return _u
}

// SetNillableBuiltin sets the "builtin" field if the given value is not nil.
func (_u *AdminRoleUpdateOne) SetNillableBuiltin(v *bool) *AdminRoleUpdateOne {
	if v != nil {
		_u.SetBuiltin(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminRoleUpdateOne) SetUpdatedAt(v time.Time) *AdminRoleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AdminRoleMutation object of the builder.
func (_u *AdminRoleUpdateOne) Mutation() *AdminRoleMutation {
	return _u.mutation
}

// Where appends a list predicates to the AdminRoleUpdate builder.
func (_u *AdminRoleUpdateOne) Where(ps ...predicate.AdminRole) *AdminRoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminRoleUpdateOne) Select(field string, fields ...string) *AdminRoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminRole entity.
func (_u *AdminRoleUpdateOne) Save(ctx context.Context) (*AdminRole, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminRoleUpdateOne) SaveX(ctx context.Context) *AdminRole {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminRoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminRoleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adminrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminRoleUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := adminrole.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "AdminRole.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := adminrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AdminRole.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := adminrole.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "AdminRole.description": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminRoleUpdateOne) sqlSave(ctx context.Context) (_node *AdminRole, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminrole.Table, adminrole.Columns, sqlgraph.NewFieldSpec(adminrole.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminrole.FieldID)
		for _, f := range fields {
			if !adminrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(adminrole.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(adminrole.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(adminrole.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(adminrole.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Builtin(); ok {
		_spec.SetField(adminrole.FieldBuiltin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminrole.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AdminRole{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
