// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/adminuserrole"
	"server/internal/data/model/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdminUserRoleUpdate is the builder for updating AdminUserRole entities.
type AdminUserRoleUpdate struct {
	config
	hooks    []Hook
	mutation *AdminUserRoleMutation
}

// Where appends a list predicates to the AdminUserRoleUpdate builder.
func (_u *AdminUserRoleUpdate) Where(ps ...predicate.AdminUserRole) *AdminUserRoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAdminUserID sets the "admin_user_id" field.
func (_u *AdminUserRoleUpdate) SetAdminUserID(v int) *AdminUserRoleUpdate {
	_u.mutation.ResetAdminUserID()
	_u.mutation.SetAdminUserID(v)
	return _u
}

// SetNillableAdminUserID sets the "admin_user_id" field if the given value is not nil.
func (_u *AdminUserRoleUpdate) SetNillableAdminUserID(v *int) *AdminUserRoleUpdate {
	if v != nil {
		_u.SetAdminUserID(*v)
	}
	return _u
}

// AddAdminUserID adds value to the "admin_user_id" field.
func (_u *AdminUserRoleUpdate) AddAdminUserID(v int) *AdminUserRoleUpdate {
	_u.mutation.AddAdminUserID(v)
	return _u
}

// SetAdminRoleID sets the "admin_role_id" field.
func (_u *AdminUserRoleUpdate) SetAdminRoleID(v int) *AdminUserRoleUpdate {
	_u.mutation.ResetAdminRoleID()
	_u.mutation.SetAdminRoleID(v)
	return _u
}

// SetNillableAdminRoleID sets the "admin_role_id" field if the given value is not nil.
func (_u *AdminUserRoleUpdate) SetNillableAdminRoleID(v *int) *AdminUserRoleUpdate {
	if v != nil {
		_u.SetAdminRoleID(*v)
	}
	return _u
}

// AddAdminRoleID adds value to the "admin_role_id" field.
func (_u *AdminUserRoleUpdate) AddAdminRoleID(v int) *AdminUserRoleUpdate {
	_u.mutation.AddAdminRoleID(v)
	return _u
}

// Mutation returns the AdminUserRoleMutation object of the builder.
func (_u *AdminUserRoleUpdate) Mutation() *AdminUserRoleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminUserRoleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminUserRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminUserRoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminUserRoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AdminUserRoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(adminuserrole.Table, adminuserrole.Columns, sqlgraph.NewFieldSpec(adminuserrole.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AdminUserID(); ok {
		_spec.SetField(adminuserrole.FieldAdminUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdminUserID(); ok {
		_spec.AddField(adminuserrole.FieldAdminUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AdminRoleID(); ok {
		_spec.SetField(adminuserrole.FieldAdminRoleID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdminRoleID(); ok {
		_spec.AddField(adminuserrole.FieldAdminRoleID, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminuserrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminUserRoleUpdateOne is the builder for updating a single AdminUserRole entity.
type AdminUserRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminUserRoleMutation
}

// SetAdminUserID sets the "admin_user_id" field.
func (_u *AdminUserRoleUpdateOne) SetAdminUserID(v int) *AdminUserRoleUpdateOne {
	_u.mutation.ResetAdminUserID()
	_u.mutation.SetAdminUserID(v)
	return _u
}

// SetNillableAdminUserID sets the "admin_user_id" field if the given value is not nil.
func (_u *AdminUserRoleUpdateOne) SetNillableAdminUserID(v *int) *AdminUserRoleUpdateOne {
	if v != nil {
		_u.SetAdminUserID(*v)
	}
	return _u
}

// AddAdminUserID adds value to the "admin_user_id" field.
func (_u *AdminUserRoleUpdateOne) AddAdminUserID(v int) *AdminUserRoleUpdateOne {
	_u.mutation.AddAdminUserID(v)
	return _u
}

// SetAdminRoleID sets the "admin_role_id" field.
func (_u *AdminUserRoleUpdateOne) SetAdminRoleID(v int) *AdminUserRoleUpdateOne {
	_u.mutation.ResetAdminRoleID()
	_u.mutation.SetAdminRoleID(v)
	return _u
}

// SetNillableAdminRoleID sets the "admin_role_id" field if the given value is not nil.
func (_u *AdminUserRoleUpdateOne) SetNillableAdminRoleID(v *int) *AdminUserRoleUpdateOne {
	if v != nil {
		_u.SetAdminRoleID(*v)
	}
	return _u
}

// AddAdminRoleID adds value to the "admin_role_id" field.
func (_u *AdminUserRoleUpdateOne) AddAdminRoleID(v int) *AdminUserRoleUpdateOne {
	_u.mutation.AddAdminRoleID(v)
	return _u
}

// Mutation returns the AdminUserRoleMutation object of the builder.
func (_u *AdminUserRoleUpdateOne) Mutation() *AdminUserRoleMutation {
	return _u.mutation
}

// Where appends a list predicates to the AdminUserRoleUpdate builder.
func (_u *AdminUserRoleUpdateOne) Where(ps ...predicate.AdminUserRole) *AdminUserRoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminUserRoleUpdateOne) Select(field string, fields ...string) *AdminUserRoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminUserRole entity.
func (_u *AdminUserRoleUpdateOne) Save(ctx context.Context) (*AdminUserRole, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminUserRoleUpdateOne) SaveX(ctx context.Context) *AdminUserRole {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminUserRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminUserRoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AdminUserRoleUpdateOne) sqlSave(ctx context.Context) (_node *AdminUserRole, err error) {
	_spec := sqlgraph.NewUpdateSpec(adminuserrole.Table, adminuserrole.Columns, sqlgraph.NewFieldSpec(adminuserrole.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminUserRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminuserrole.FieldID)
		for _, f := range fields {
			if !adminuserrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminuserrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AdminUserID(); ok {
		_spec.SetField(adminuserrole.FieldAdminUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdminUserID(); ok {
		_spec.AddField(adminuserrole.FieldAdminUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AdminRoleID(); ok {
		_spec.SetField(adminuserrole.FieldAdminRoleID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdminRoleID(); ok {
		_spec.AddField(adminuserrole.FieldAdminRoleID, field.TypeInt, value)
	}
	_node = &AdminUserRole{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminuserrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
