// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/adminpermission"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdminPermissionCreate is the builder for creating a AdminPermission entity.
type AdminPermissionCreate struct {
	config
	mutation *AdminPermissionMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (_c *AdminPermissionCreate) SetKey(v string) *AdminPermissionCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetName sets the "name" field.
func (_c *AdminPermissionCreate) SetName(v string) *AdminPermissionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetGroup sets the "group" field.
func (_c *AdminPermissionCreate) SetGroup(v string) *AdminPermissionCreate {
	_c.mutation.SetGroup(v)
	return _c
}

// SetNillableGroup sets the "group" field if the given value is not nil.
func (_c *AdminPermissionCreate) SetNillableGroup(v *string) *AdminPermissionCreate {
	if v != nil {
		_c.SetGroup(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *AdminPermissionCreate) SetDescription(v string) *AdminPermissionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *AdminPermissionCreate) SetNillableDescription(v *string) *AdminPermissionCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetBuiltin sets the "builtin" field.
func (_c *AdminPermissionCreate) SetBuiltin(v bool) *AdminPermissionCreate {
	_c.mutation.SetBuiltin(v)
	return _c
}

// SetNillableBuiltin sets the "builtin" field if the given value is not nil.
func (_c *AdminPermissionCreate) SetNillableBuiltin(v *bool) *AdminPermissionCreate {
	if v != nil {
		_c.SetBuiltin(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdminPermissionCreate) SetCreatedAt(v time.Time) *AdminPermissionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdminPermissionCreate) SetNillableCreatedAt(v *time.Time) *AdminPermissionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AdminPermissionCreate) SetUpdatedAt(v time.Time) *AdminPermissionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AdminPermissionCreate) SetNillableUpdatedAt(v *time.Time) *AdminPermissionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the AdminPermissionMutation object of the builder.
func (_c *AdminPermissionCreate) Mutation() *AdminPermissionMutation {
	return _c.mutation
}

// Save creates the AdminPermission in the database.
func (_c *AdminPermissionCreate) Save(ctx context.Context) (*AdminPermission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdminPermissionCreate) SaveX(ctx context.Context) *AdminPermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminPermissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminPermissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdminPermissionCreate) defaults() {
	if _, ok := _c.mutation.Group(); !ok {
		v := adminpermission.DefaultGroup
		_c.mutation.SetGroup(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := adminpermission.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Builtin(); !ok {
		v := adminpermission.DefaultBuiltin
		_c.mutation.SetBuiltin(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := adminpermission.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := adminpermission.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdminPermissionCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "AdminPermission.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := adminpermission.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "AdminPermission.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AdminPermission.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := adminpermission.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AdminPermission.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Group(); ok {
		if err := adminpermission.GroupValidator(v); err != nil {
			return &ValidationError{Name: "group", err: fmt.Errorf(`ent: validator failed for field "AdminPermission.group": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := adminpermission.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "AdminPermission.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Builtin(); !ok {
		return &ValidationError{Name: "builtin", err: errors.New(`ent: missing required field "AdminPermission.builtin"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AdminPermission.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AdminPermission.updated_at"`)}
	}
	return nil
}

func (_c *AdminPermissionCreate) sqlSave(ctx context.Context) (*AdminPermission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdminPermissionCreate) createSpec() (*AdminPermission, *sqlgraph.CreateSpec) {
	var (
		_node = &AdminPermission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adminpermission.Table, sqlgraph.NewFieldSpec(adminpermission.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(adminpermission.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(adminpermission.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Group(); ok {
		_spec.SetField(adminpermission.FieldGroup, field.TypeString, value)
		_node.Group = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(adminpermission.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Builtin(); ok {
		_spec.SetField(adminpermission.FieldBuiltin, field.TypeBool, value)
		_node.Builtin = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(adminpermission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(adminpermission.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// AdminPermissionCreateBulk is the builder for creating many AdminPermission entities in bulk.
type AdminPermissionCreateBulk struct {
	config
	err      error
	builders []*AdminPermissionCreate
}

// Save creates the AdminPermission entities in the database.
func (_c *AdminPermissionCreateBulk) Save(ctx context.Context) ([]*AdminPermission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AdminPermission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdminPermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdminPermissionCreateBulk) SaveX(ctx context.Context) []*AdminPermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminPermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminPermissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
