// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/invitecode"
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InviteCodeUpdate is the builder for updating InviteCode entities.
type InviteCodeUpdate struct {
	config
	hooks    []Hook
	mutation *InviteCodeMutation
}

// Where appends a list predicates to the InviteCodeUpdate builder.
func (_u *InviteCodeUpdate) Where(ps ...predicate.InviteCode) *InviteCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *InviteCodeUpdate) SetCode(v string) *InviteCodeUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *InviteCodeUpdate) SetNillableCode(v *string) *InviteCodeUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetMaxUses sets the "max_uses" field.
func (_u *InviteCodeUpdate) SetMaxUses(v int) *InviteCodeUpdate {
	_u.mutation.ResetMaxUses()
	_u.mutation.SetMaxUses(v)
	return _u
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_u *InviteCodeUpdate) SetNillableMaxUses(v *int) *InviteCodeUpdate {
	if v != nil {
		_u.SetMaxUses(*v)
	}
	return _u
}

// AddMaxUses adds value to the "max_uses" field.
func (_u *InviteCodeUpdate) AddMaxUses(v int) *InviteCodeUpdate {
	_u.mutation.AddMaxUses(v)
	return _u
}

// SetUsedCount sets the "used_count" field.
func (_u *InviteCodeUpdate) SetUsedCount(v int) *InviteCodeUpdate {
	_u.mutation.ResetUsedCount()
	_u.mutation.SetUsedCount(v)
	return _u
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_u *InviteCodeUpdate) SetNillableUsedCount(v *int) *InviteCodeUpdate {
	if v != nil {
		_u.SetUsedCount(*v)
	}
	return _u
}

// AddUsedCount adds value to the "used_count" field.
func (_u *InviteCodeUpdate) AddUsedCount(v int) *InviteCodeUpdate {
	_u.mutation.AddUsedCount(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *InviteCodeUpdate) SetExpiresAt(v time.Time) *InviteCodeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *InviteCodeUpdate) SetNillableExpiresAt(v *time.Time) *InviteCodeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *InviteCodeUpdate) ClearExpiresAt() *InviteCodeUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *InviteCodeUpdate) SetDisabled(v bool) *InviteCodeUpdate {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *InviteCodeUpdate) SetNillableDisabled(v *bool) *InviteCodeUpdate {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InviteCodeUpdate) SetUpdatedAt(v time.Time) *InviteCodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the InviteCodeMutation object of the builder.
func (_u *InviteCodeUpdate) Mutation() *InviteCodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InviteCodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InviteCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InviteCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InviteCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InviteCodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invitecode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InviteCodeUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := invitecode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "InviteCode.code": %w`, err)}
		}
	}
	return nil
}

func (_u *InviteCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitecode.Table, invitecode.Columns, sqlgraph.NewFieldSpec(invitecode.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(invitecode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxUses(); ok {
		_spec.SetField(invitecode.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUses(); ok {
		_spec.AddField(invitecode.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UsedCount(); ok {
		_spec.SetField(invitecode.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsedCount(); ok {
		_spec.AddField(invitecode.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(invitecode.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(invitecode.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(invitecode.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invitecode.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitecode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InviteCodeUpdateOne is the builder for updating a single InviteCode entity.
type InviteCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InviteCodeMutation
}

// SetCode sets the "code" field.
func (_u *InviteCodeUpdateOne) SetCode(v string) *InviteCodeUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *InviteCodeUpdateOne) SetNillableCode(v *string) *InviteCodeUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetMaxUses sets the "max_uses" field.
func (_u *InviteCodeUpdateOne) SetMaxUses(v int) *InviteCodeUpdateOne {
	_u.mutation.ResetMaxUses()
	_u.mutation.SetMaxUses(v)
	return _u
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_u *InviteCodeUpdateOne) SetNillableMaxUses(v *int) *InviteCodeUpdateOne {
	if v != nil {
		_u.SetMaxUses(*v)
	}
	return _u
}

// AddMaxUses adds value to the "max_uses" field.
func (_u *InviteCodeUpdateOne) AddMaxUses(v int) *InviteCodeUpdateOne {
	_u.mutation.AddMaxUses(v)
	return _u
}

// SetUsedCount sets the "used_count" field.
func (_u *InviteCodeUpdateOne) SetUsedCount(v int) *InviteCodeUpdateOne {
	_u.mutation.ResetUsedCount()
	_u.mutation.SetUsedCount(v)
	return _u
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_u *InviteCodeUpdateOne) SetNillableUsedCount(v *int) *InviteCodeUpdateOne {
	if v != nil {
		_u.SetUsedCount(*v)
	}
	return _u
}

// AddUsedCount adds value to the "used_count" field.
func (_u *InviteCodeUpdateOne) AddUsedCount(v int) *InviteCodeUpdateOne {
	_u.mutation.AddUsedCount(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *InviteCodeUpdateOne) SetExpiresAt(v time.Time) *InviteCodeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *InviteCodeUpdateOne) SetNillableExpiresAt(v *time.Time) *InviteCodeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *InviteCodeUpdateOne) ClearExpiresAt() *InviteCodeUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *InviteCodeUpdateOne) SetDisabled(v bool) *InviteCodeUpdateOne {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *InviteCodeUpdateOne) SetNillableDisabled(v *bool) *InviteCodeUpdateOne {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InviteCodeUpdateOne) SetUpdatedAt(v time.Time) *InviteCodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the InviteCodeMutation object of the builder.
func (_u *InviteCodeUpdateOne) Mutation() *InviteCodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the InviteCodeUpdate builder.
func (_u *InviteCodeUpdateOne) Where(ps ...predicate.InviteCode) *InviteCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InviteCodeUpdateOne) Select(field string, fields ...string) *InviteCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InviteCode entity.
func (_u *InviteCodeUpdateOne) Save(ctx context.Context) (*InviteCode, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InviteCodeUpdateOne) SaveX(ctx context.Context) *InviteCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InviteCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InviteCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InviteCodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invitecode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InviteCodeUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := invitecode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "InviteCode.code": %w`, err)}
		}
	}
	return nil
}

func (_u *InviteCodeUpdateOne) sqlSave(ctx context.Context) (_node *InviteCode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitecode.Table, invitecode.Columns, sqlgraph.NewFieldSpec(invitecode.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InviteCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invitecode.FieldID)
		for _, f := range fields {
			if !invitecode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invitecode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(invitecode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxUses(); ok {
		_spec.SetField(invitecode.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUses(); ok {
		_spec.AddField(invitecode.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UsedCount(); ok {
		_spec.SetField(invitecode.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsedCount(); ok {
		_spec.AddField(invitecode.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(invitecode.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(invitecode.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(invitecode.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invitecode.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &InviteCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitecode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
