// Code generated by ent, DO NOT EDIT.

package ent

import (
	"server/internal/data/model/ent/adminuser"
	"server/internal/data/model/ent/invitecode"
	"server/internal/data/model/ent/user"
	"server/internal/data/model/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminuserFields := schema.AdminUser{}.Fields()
	_ = adminuserFields
	// adminuserDescUsername is the schema descriptor for username field.
	adminuserDescUsername := adminuserFields[0].Descriptor()
	// adminuser.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	adminuser.UsernameValidator = func() func(string) error {
		validators := adminuserDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// adminuserDescPasswordHash is the schema descriptor for password_hash field.
	adminuserDescPasswordHash := adminuserFields[1].Descriptor()
	// adminuser.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	adminuser.PasswordHashValidator = adminuserDescPasswordHash.Validators[0].(func(string) error)
	// adminuserDescLevel is the schema descriptor for level field.
	adminuserDescLevel := adminuserFields[2].Descriptor()
	// adminuser.DefaultLevel holds the default value on creation for the level field.
	adminuser.DefaultLevel = adminuserDescLevel.Default.(int8)
	// adminuserDescDisabled is the schema descriptor for disabled field.
	adminuserDescDisabled := adminuserFields[4].Descriptor()
	// adminuser.DefaultDisabled holds the default value on creation for the disabled field.
	adminuser.DefaultDisabled = adminuserDescDisabled.Default.(bool)
	// adminuserDescCreatedAt is the schema descriptor for created_at field.
	adminuserDescCreatedAt := adminuserFields[6].Descriptor()
	// adminuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	adminuser.DefaultCreatedAt = adminuserDescCreatedAt.Default.(func() time.Time)
	// adminuserDescUpdatedAt is the schema descriptor for updated_at field.
	adminuserDescUpdatedAt := adminuserFields[7].Descriptor()
	// adminuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	adminuser.DefaultUpdatedAt = adminuserDescUpdatedAt.Default.(func() time.Time)
	// adminuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	adminuser.UpdateDefaultUpdatedAt = adminuserDescUpdatedAt.UpdateDefault.(func() time.Time)
	invitecodeFields := schema.InviteCode{}.Fields()
	_ = invitecodeFields
	// invitecodeDescCode is the schema descriptor for code field.
	invitecodeDescCode := invitecodeFields[0].Descriptor()
	// invitecode.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	invitecode.CodeValidator = func() func(string) error {
		validators := invitecodeDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// invitecodeDescMaxUses is the schema descriptor for max_uses field.
	invitecodeDescMaxUses := invitecodeFields[1].Descriptor()
	// invitecode.DefaultMaxUses holds the default value on creation for the max_uses field.
	invitecode.DefaultMaxUses = invitecodeDescMaxUses.Default.(int)
	// invitecodeDescUsedCount is the schema descriptor for used_count field.
	invitecodeDescUsedCount := invitecodeFields[2].Descriptor()
	// invitecode.DefaultUsedCount holds the default value on creation for the used_count field.
	invitecode.DefaultUsedCount = invitecodeDescUsedCount.Default.(int)
	// invitecodeDescDisabled is the schema descriptor for disabled field.
	invitecodeDescDisabled := invitecodeFields[4].Descriptor()
	// invitecode.DefaultDisabled holds the default value on creation for the disabled field.
	invitecode.DefaultDisabled = invitecodeDescDisabled.Default.(bool)
	// invitecodeDescCreatedAt is the schema descriptor for created_at field.
	invitecodeDescCreatedAt := invitecodeFields[5].Descriptor()
	// invitecode.DefaultCreatedAt holds the default value on creation for the created_at field.
	invitecode.DefaultCreatedAt = invitecodeDescCreatedAt.Default.(func() time.Time)
	// invitecodeDescUpdatedAt is the schema descriptor for updated_at field.
	invitecodeDescUpdatedAt := invitecodeFields[6].Descriptor()
	// invitecode.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	invitecode.DefaultUpdatedAt = invitecodeDescUpdatedAt.Default.(func() time.Time)
	// invitecode.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	invitecode.UpdateDefaultUpdatedAt = invitecodeDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescInviteCode is the schema descriptor for invite_code field.
	userDescInviteCode := userFields[2].Descriptor()
	// user.InviteCodeValidator is a validator for the "invite_code" field. It is called by the builders before save.
	user.InviteCodeValidator = userDescInviteCode.Validators[0].(func(string) error)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[3].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(int8)
	// userDescDisabled is the schema descriptor for disabled field.
	userDescDisabled := userFields[5].Descriptor()
	// user.DefaultDisabled holds the default value on creation for the disabled field.
	user.DefaultDisabled = userDescDisabled.Default.(bool)
	// userDescPoints is the schema descriptor for points field.
	userDescPoints := userFields[7].Descriptor()
	// user.DefaultPoints holds the default value on creation for the points field.
	user.DefaultPoints = userDescPoints.Default.(int64)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[9].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[10].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
