// Code generated by ent, DO NOT EDIT.

package ent

import (
	"server/internal/data/model/ent/adminpermission"
	"server/internal/data/model/ent/adminrole"
	"server/internal/data/model/ent/adminrolepermission"
	"server/internal/data/model/ent/adminuser"
	"server/internal/data/model/ent/adminuserrole"
	"server/internal/data/model/ent/user"
	"server/internal/data/model/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminpermissionFields := schema.AdminPermission{}.Fields()
	_ = adminpermissionFields
	// adminpermissionDescKey is the schema descriptor for key field.
	adminpermissionDescKey := adminpermissionFields[0].Descriptor()
	// adminpermission.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	adminpermission.KeyValidator = func() func(string) error {
		validators := adminpermissionDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// adminpermissionDescName is the schema descriptor for name field.
	adminpermissionDescName := adminpermissionFields[1].Descriptor()
	// adminpermission.NameValidator is a validator for the "name" field. It is called by the builders before save.
	adminpermission.NameValidator = func() func(string) error {
		validators := adminpermissionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// adminpermissionDescGroup is the schema descriptor for group field.
	adminpermissionDescGroup := adminpermissionFields[2].Descriptor()
	// adminpermission.DefaultGroup holds the default value on creation for the group field.
	adminpermission.DefaultGroup = adminpermissionDescGroup.Default.(string)
	// adminpermission.GroupValidator is a validator for the "group" field. It is called by the builders before save.
	adminpermission.GroupValidator = adminpermissionDescGroup.Validators[0].(func(string) error)
	// adminpermissionDescDescription is the schema descriptor for description field.
	adminpermissionDescDescription := adminpermissionFields[3].Descriptor()
	// adminpermission.DefaultDescription holds the default value on creation for the description field.
	adminpermission.DefaultDescription = adminpermissionDescDescription.Default.(string)
	// adminpermission.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	adminpermission.DescriptionValidator = adminpermissionDescDescription.Validators[0].(func(string) error)
	// adminpermissionDescBuiltin is the schema descriptor for builtin field.
	adminpermissionDescBuiltin := adminpermissionFields[4].Descriptor()
	// adminpermission.DefaultBuiltin holds the default value on creation for the builtin field.
	adminpermission.DefaultBuiltin = adminpermissionDescBuiltin.Default.(bool)
	// adminpermissionDescCreatedAt is the schema descriptor for created_at field.
	adminpermissionDescCreatedAt := adminpermissionFields[5].Descriptor()
	// adminpermission.DefaultCreatedAt holds the default value on creation for the created_at field.
	adminpermission.DefaultCreatedAt = adminpermissionDescCreatedAt.Default.(func() time.Time)
	// adminpermissionDescUpdatedAt is the schema descriptor for updated_at field.
	adminpermissionDescUpdatedAt := adminpermissionFields[6].Descriptor()
	// adminpermission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	adminpermission.DefaultUpdatedAt = adminpermissionDescUpdatedAt.Default.(func() time.Time)
	// adminpermission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	adminpermission.UpdateDefaultUpdatedAt = adminpermissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	adminroleFields := schema.AdminRole{}.Fields()
	_ = adminroleFields
	// adminroleDescKey is the schema descriptor for key field.
	adminroleDescKey := adminroleFields[0].Descriptor()
	// adminrole.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	adminrole.KeyValidator = func() func(string) error {
		validators := adminroleDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// adminroleDescName is the schema descriptor for name field.
	adminroleDescName := adminroleFields[1].Descriptor()
	// adminrole.NameValidator is a validator for the "name" field. It is called by the builders before save.
	adminrole.NameValidator = func() func(string) error {
		validators := adminroleDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// adminroleDescDescription is the schema descriptor for description field.
	adminroleDescDescription := adminroleFields[2].Descriptor()
	// adminrole.DefaultDescription holds the default value on creation for the description field.
	adminrole.DefaultDescription = adminroleDescDescription.Default.(string)
	// adminrole.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	adminrole.DescriptionValidator = adminroleDescDescription.Validators[0].(func(string) error)
	// adminroleDescBuiltin is the schema descriptor for builtin field.
	adminroleDescBuiltin := adminroleFields[3].Descriptor()
	// adminrole.DefaultBuiltin holds the default value on creation for the builtin field.
	adminrole.DefaultBuiltin = adminroleDescBuiltin.Default.(bool)
	// adminroleDescCreatedAt is the schema descriptor for created_at field.
	adminroleDescCreatedAt := adminroleFields[4].Descriptor()
	// adminrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	adminrole.DefaultCreatedAt = adminroleDescCreatedAt.Default.(func() time.Time)
	// adminroleDescUpdatedAt is the schema descriptor for updated_at field.
	adminroleDescUpdatedAt := adminroleFields[5].Descriptor()
	// adminrole.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	adminrole.DefaultUpdatedAt = adminroleDescUpdatedAt.Default.(func() time.Time)
	// adminrole.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	adminrole.UpdateDefaultUpdatedAt = adminroleDescUpdatedAt.UpdateDefault.(func() time.Time)
	adminrolepermissionFields := schema.AdminRolePermission{}.Fields()
	_ = adminrolepermissionFields
	// adminrolepermissionDescCreatedAt is the schema descriptor for created_at field.
	adminrolepermissionDescCreatedAt := adminrolepermissionFields[2].Descriptor()
	// adminrolepermission.DefaultCreatedAt holds the default value on creation for the created_at field.
	adminrolepermission.DefaultCreatedAt = adminrolepermissionDescCreatedAt.Default.(func() time.Time)
	adminuserFields := schema.AdminUser{}.Fields()
	_ = adminuserFields
	// adminuserDescUsername is the schema descriptor for username field.
	adminuserDescUsername := adminuserFields[0].Descriptor()
	// adminuser.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	adminuser.UsernameValidator = func() func(string) error {
		validators := adminuserDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// adminuserDescPasswordHash is the schema descriptor for password_hash field.
	adminuserDescPasswordHash := adminuserFields[1].Descriptor()
	// adminuser.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	adminuser.PasswordHashValidator = adminuserDescPasswordHash.Validators[0].(func(string) error)
	// adminuserDescDisabled is the schema descriptor for disabled field.
	adminuserDescDisabled := adminuserFields[2].Descriptor()
	// adminuser.DefaultDisabled holds the default value on creation for the disabled field.
	adminuser.DefaultDisabled = adminuserDescDisabled.Default.(bool)
	// adminuserDescCreatedAt is the schema descriptor for created_at field.
	adminuserDescCreatedAt := adminuserFields[4].Descriptor()
	// adminuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	adminuser.DefaultCreatedAt = adminuserDescCreatedAt.Default.(func() time.Time)
	// adminuserDescUpdatedAt is the schema descriptor for updated_at field.
	adminuserDescUpdatedAt := adminuserFields[5].Descriptor()
	// adminuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	adminuser.DefaultUpdatedAt = adminuserDescUpdatedAt.Default.(func() time.Time)
	// adminuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	adminuser.UpdateDefaultUpdatedAt = adminuserDescUpdatedAt.UpdateDefault.(func() time.Time)
	adminuserroleFields := schema.AdminUserRole{}.Fields()
	_ = adminuserroleFields
	// adminuserroleDescCreatedAt is the schema descriptor for created_at field.
	adminuserroleDescCreatedAt := adminuserroleFields[2].Descriptor()
	// adminuserrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	adminuserrole.DefaultCreatedAt = adminuserroleDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescDisabled is the schema descriptor for disabled field.
	userDescDisabled := userFields[2].Descriptor()
	// user.DefaultDisabled holds the default value on creation for the disabled field.
	user.DefaultDisabled = userDescDisabled.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
