// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.opentelemetry.io/otel/sdk/trace"
	"server/internal/biz"
	"server/internal/conf"
	"server/internal/data"
	"server/internal/server"
	"server/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, tracerProvider *trace.TracerProvider) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	authRepo := data.NewAuthRepo(dataData, logger)
	tokenGenerator := data.NewTokenGenerator(confData, logger)
	authUsecase := biz.NewAuthUsecase(authRepo, tokenGenerator, logger, tracerProvider)
	adminAuthRepo := data.NewAdminAuthRepo(dataData, logger)
	adminTokenGenerator := data.NewAdminTokenGenerator(confData, logger)
	adminAuthUsecase := biz.NewAdminAuthUsecase(adminAuthRepo, adminTokenGenerator, logger, tracerProvider)
	userAdminRepo := data.NewUserAdminRepo(dataData, logger)
	userAdminUsecase := biz.NewUserAdminUsecase(userAdminRepo, logger, tracerProvider)
	rbacRepo := data.NewRBACRepo(dataData, logger)
	rbacUsecase := biz.NewRBACUsecase(rbacRepo)
	jsonrpcService := service.NewJsonrpcService(authUsecase, adminAuthUsecase, userAdminUsecase, rbacUsecase, adminAuthRepo, logger)
	grpcServer := server.NewGRPCServer(confServer, logger, jsonrpcService, tracerProvider, dataData)
	httpServer := server.NewHTTPServer(confServer, logger, jsonrpcService, tracerProvider, dataData, confData)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
