// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/jsonrpc/v1/jsonrpc.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------------
// GET 版本
// --------------------
type GetJsonrpcRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// /rpc/{url} 里的 path 变量
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// JSON-RPC 版本，通常 "2.0"
	Jsonrpc string `protobuf:"bytes,2,opt,name=jsonrpc,proto3" json:"jsonrpc,omitempty"`
	// JSON-RPC id，用 string 存，前端是数字也能转成字符串
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// 可选：method & params 也可以跟在 query 里（不强制）
	Method        string           `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Params        *structpb.Struct `protobuf:"bytes,5,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJsonrpcRequest) Reset() {
	*x = GetJsonrpcRequest{}
	mi := &file_api_jsonrpc_v1_jsonrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJsonrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJsonrpcRequest) ProtoMessage() {}

func (x *GetJsonrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_jsonrpc_v1_jsonrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJsonrpcRequest.ProtoReflect.Descriptor instead.
func (*GetJsonrpcRequest) Descriptor() ([]byte, []int) {
	return file_api_jsonrpc_v1_jsonrpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetJsonrpcRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetJsonrpcRequest) GetJsonrpc() string {
	if x != nil {
		return x.Jsonrpc
	}
	return ""
}

func (x *GetJsonrpcRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetJsonrpcRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *GetJsonrpcRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

type GetJsonrpcReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jsonrpc       string                 `protobuf:"bytes,1,opt,name=jsonrpc,proto3" json:"jsonrpc,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Result        *JsonrpcResult         `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJsonrpcReply) Reset() {
	*x = GetJsonrpcReply{}
	mi := &file_api_jsonrpc_v1_jsonrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJsonrpcReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJsonrpcReply) ProtoMessage() {}

func (x *GetJsonrpcReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_jsonrpc_v1_jsonrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJsonrpcReply.ProtoReflect.Descriptor instead.
func (*GetJsonrpcReply) Descriptor() ([]byte, []int) {
	return file_api_jsonrpc_v1_jsonrpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetJsonrpcReply) GetJsonrpc() string {
	if x != nil {
		return x.Jsonrpc
	}
	return ""
}

func (x *GetJsonrpcReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetJsonrpcReply) GetResult() *JsonrpcResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetJsonrpcReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// --------------------
// POST 版本（推荐）
// --------------------
type PostJsonrpcRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// /rpc/{url} 里的 path 变量，用于区分不同业务域，比如 "auth"、"collision"、"ml" 等
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// JSON-RPC 标准字段
	Jsonrpc       string           `protobuf:"bytes,2,opt,name=jsonrpc,proto3" json:"jsonrpc,omitempty"` // 一般是 "2.0"
	Method        string           `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`   // 比如: "system.ping" / "collision.plan.list" / "collision.game.next"
	Params        *structpb.Struct `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`   // 原始 params
	Id            string           `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`           // JSON-RPC id，不带 id 则可以视为通知
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostJsonrpcRequest) Reset() {
	*x = PostJsonrpcRequest{}
	mi := &file_api_jsonrpc_v1_jsonrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostJsonrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostJsonrpcRequest) ProtoMessage() {}

func (x *PostJsonrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_jsonrpc_v1_jsonrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostJsonrpcRequest.ProtoReflect.Descriptor instead.
func (*PostJsonrpcRequest) Descriptor() ([]byte, []int) {
	return file_api_jsonrpc_v1_jsonrpc_proto_rawDescGZIP(), []int{2}
}

func (x *PostJsonrpcRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PostJsonrpcRequest) GetJsonrpc() string {
	if x != nil {
		return x.Jsonrpc
	}
	return ""
}

func (x *PostJsonrpcRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PostJsonrpcRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *PostJsonrpcRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PostJsonrpcReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jsonrpc       string                 `protobuf:"bytes,1,opt,name=jsonrpc,proto3" json:"jsonrpc,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Result        *JsonrpcResult         `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostJsonrpcReply) Reset() {
	*x = PostJsonrpcReply{}
	mi := &file_api_jsonrpc_v1_jsonrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostJsonrpcReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostJsonrpcReply) ProtoMessage() {}

func (x *PostJsonrpcReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_jsonrpc_v1_jsonrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostJsonrpcReply.ProtoReflect.Descriptor instead.
func (*PostJsonrpcReply) Descriptor() ([]byte, []int) {
	return file_api_jsonrpc_v1_jsonrpc_proto_rawDescGZIP(), []int{3}
}

func (x *PostJsonrpcReply) GetJsonrpc() string {
	if x != nil {
		return x.Jsonrpc
	}
	return ""
}

func (x *PostJsonrpcReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PostJsonrpcReply) GetResult() *JsonrpcResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *PostJsonrpcReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// --------------------
// 通用结果封装
// --------------------
type JsonrpcResult struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 0 = 成功，非 0 = 错误
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 通用提示
	// 真正的业务数据 payload，所有 domain 统一塞到这里，
	// 比如：
	//   - system.ping         -> {"pong": "pong"}
	//   - collision.plan.list -> {"plans": [...]}
	//   - collision.game.next -> {... round & session info ...}
	Data          *structpb.Struct `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonrpcResult) Reset() {
	*x = JsonrpcResult{}
	mi := &file_api_jsonrpc_v1_jsonrpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonrpcResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonrpcResult) ProtoMessage() {}

func (x *JsonrpcResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_jsonrpc_v1_jsonrpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonrpcResult.ProtoReflect.Descriptor instead.
func (*JsonrpcResult) Descriptor() ([]byte, []int) {
	return file_api_jsonrpc_v1_jsonrpc_proto_rawDescGZIP(), []int{4}
}

func (x *JsonrpcResult) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JsonrpcResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JsonrpcResult) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_jsonrpc_v1_jsonrpc_proto protoreflect.FileDescriptor

const file_api_jsonrpc_v1_jsonrpc_proto_rawDesc = "" +
	"\n" +
	"\x1capi/jsonrpc/v1/jsonrpc.proto\x12\n" +
	"jsonrpc.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x98\x01\n" +
	"\x11GetJsonrpcRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x18\n" +
	"\ajsonrpc\x18\x02 \x01(\tR\ajsonrpc\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12/\n" +
	"\x06params\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06params\"\x84\x01\n" +
	"\x0fGetJsonrpcReply\x12\x18\n" +
	"\ajsonrpc\x18\x01 \x01(\tR\ajsonrpc\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x121\n" +
	"\x06result\x18\x03 \x01(\v2\x19.jsonrpc.v1.JsonrpcResultR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x99\x01\n" +
	"\x12PostJsonrpcRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x18\n" +
	"\ajsonrpc\x18\x02 \x01(\tR\ajsonrpc\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12/\n" +
	"\x06params\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06params\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\"\x85\x01\n" +
	"\x10PostJsonrpcReply\x12\x18\n" +
	"\ajsonrpc\x18\x01 \x01(\tR\ajsonrpc\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x121\n" +
	"\x06result\x18\x03 \x01(\v2\x19.jsonrpc.v1.JsonrpcResultR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"j\n" +
	"\rJsonrpcResult\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data2\xcb\x01\n" +
	"\aJsonrpc\x12\\\n" +
	"\n" +
	"GetJsonrpc\x12\x1d.jsonrpc.v1.GetJsonrpcRequest\x1a\x1b.jsonrpc.v1.GetJsonrpcReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/rpc/{url}\x12b\n" +
	"\vPostJsonrpc\x12\x1e.jsonrpc.v1.PostJsonrpcRequest\x1a\x1c.jsonrpc.v1.PostJsonrpcReply\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/rpc/{url}B\x1aZ\x18server/api/jsonrpc/v1;v1b\x06proto3"

var (
	file_api_jsonrpc_v1_jsonrpc_proto_rawDescOnce sync.Once
	file_api_jsonrpc_v1_jsonrpc_proto_rawDescData []byte
)

func file_api_jsonrpc_v1_jsonrpc_proto_rawDescGZIP() []byte {
	file_api_jsonrpc_v1_jsonrpc_proto_rawDescOnce.Do(func() {
		file_api_jsonrpc_v1_jsonrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_jsonrpc_v1_jsonrpc_proto_rawDesc), len(file_api_jsonrpc_v1_jsonrpc_proto_rawDesc)))
	})
	return file_api_jsonrpc_v1_jsonrpc_proto_rawDescData
}

var file_api_jsonrpc_v1_jsonrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_jsonrpc_v1_jsonrpc_proto_goTypes = []any{
	(*GetJsonrpcRequest)(nil),  // 0: jsonrpc.v1.GetJsonrpcRequest
	(*GetJsonrpcReply)(nil),    // 1: jsonrpc.v1.GetJsonrpcReply
	(*PostJsonrpcRequest)(nil), // 2: jsonrpc.v1.PostJsonrpcRequest
	(*PostJsonrpcReply)(nil),   // 3: jsonrpc.v1.PostJsonrpcReply
	(*JsonrpcResult)(nil),      // 4: jsonrpc.v1.JsonrpcResult
	(*structpb.Struct)(nil),    // 5: google.protobuf.Struct
}
var file_api_jsonrpc_v1_jsonrpc_proto_depIdxs = []int32{
	5, // 0: jsonrpc.v1.GetJsonrpcRequest.params:type_name -> google.protobuf.Struct
	4, // 1: jsonrpc.v1.GetJsonrpcReply.result:type_name -> jsonrpc.v1.JsonrpcResult
	5, // 2: jsonrpc.v1.PostJsonrpcRequest.params:type_name -> google.protobuf.Struct
	4, // 3: jsonrpc.v1.PostJsonrpcReply.result:type_name -> jsonrpc.v1.JsonrpcResult
	5, // 4: jsonrpc.v1.JsonrpcResult.data:type_name -> google.protobuf.Struct
	0, // 5: jsonrpc.v1.Jsonrpc.GetJsonrpc:input_type -> jsonrpc.v1.GetJsonrpcRequest
	2, // 6: jsonrpc.v1.Jsonrpc.PostJsonrpc:input_type -> jsonrpc.v1.PostJsonrpcRequest
	1, // 7: jsonrpc.v1.Jsonrpc.GetJsonrpc:output_type -> jsonrpc.v1.GetJsonrpcReply
	3, // 8: jsonrpc.v1.Jsonrpc.PostJsonrpc:output_type -> jsonrpc.v1.PostJsonrpcReply
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_jsonrpc_v1_jsonrpc_proto_init() }
func file_api_jsonrpc_v1_jsonrpc_proto_init() {
	if File_api_jsonrpc_v1_jsonrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_jsonrpc_v1_jsonrpc_proto_rawDesc), len(file_api_jsonrpc_v1_jsonrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_jsonrpc_v1_jsonrpc_proto_goTypes,
		DependencyIndexes: file_api_jsonrpc_v1_jsonrpc_proto_depIdxs,
		MessageInfos:      file_api_jsonrpc_v1_jsonrpc_proto_msgTypes,
	}.Build()
	File_api_jsonrpc_v1_jsonrpc_proto = out.File
	file_api_jsonrpc_v1_jsonrpc_proto_goTypes = nil
	file_api_jsonrpc_v1_jsonrpc_proto_depIdxs = nil
}
