// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/jsonrpc/v1/jsonrpc.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Jsonrpc_GetJsonrpc_FullMethodName  = "/jsonrpc.v1.Jsonrpc/GetJsonrpc"
	Jsonrpc_PostJsonrpc_FullMethodName = "/jsonrpc.v1.Jsonrpc/PostJsonrpc"
)

// JsonrpcClient is the client API for Jsonrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JSON-RPC 统一入口
// /rpc/{url}   <- 模块
// method       <- 动作
// params       <- 内容
type JsonrpcClient interface {
	// GET /rpc/{url}?id=xxx&jsonrpc=2.0&method=ping 之类
	GetJsonrpc(ctx context.Context, in *GetJsonrpcRequest, opts ...grpc.CallOption) (*GetJsonrpcReply, error)
	// POST /rpc/{url}
	// body 是 JSON-RPC 报文的“结构化版本”
	PostJsonrpc(ctx context.Context, in *PostJsonrpcRequest, opts ...grpc.CallOption) (*PostJsonrpcReply, error)
}

type jsonrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewJsonrpcClient(cc grpc.ClientConnInterface) JsonrpcClient {
	return &jsonrpcClient{cc}
}

func (c *jsonrpcClient) GetJsonrpc(ctx context.Context, in *GetJsonrpcRequest, opts ...grpc.CallOption) (*GetJsonrpcReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJsonrpcReply)
	err := c.cc.Invoke(ctx, Jsonrpc_GetJsonrpc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jsonrpcClient) PostJsonrpc(ctx context.Context, in *PostJsonrpcRequest, opts ...grpc.CallOption) (*PostJsonrpcReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostJsonrpcReply)
	err := c.cc.Invoke(ctx, Jsonrpc_PostJsonrpc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JsonrpcServer is the server API for Jsonrpc service.
// All implementations must embed UnimplementedJsonrpcServer
// for forward compatibility.
//
// JSON-RPC 统一入口
// /rpc/{url}   <- 模块
// method       <- 动作
// params       <- 内容
type JsonrpcServer interface {
	// GET /rpc/{url}?id=xxx&jsonrpc=2.0&method=ping 之类
	GetJsonrpc(context.Context, *GetJsonrpcRequest) (*GetJsonrpcReply, error)
	// POST /rpc/{url}
	// body 是 JSON-RPC 报文的“结构化版本”
	PostJsonrpc(context.Context, *PostJsonrpcRequest) (*PostJsonrpcReply, error)
	mustEmbedUnimplementedJsonrpcServer()
}

// UnimplementedJsonrpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJsonrpcServer struct{}

func (UnimplementedJsonrpcServer) GetJsonrpc(context.Context, *GetJsonrpcRequest) (*GetJsonrpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJsonrpc not implemented")
}
func (UnimplementedJsonrpcServer) PostJsonrpc(context.Context, *PostJsonrpcRequest) (*PostJsonrpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostJsonrpc not implemented")
}
func (UnimplementedJsonrpcServer) mustEmbedUnimplementedJsonrpcServer() {}
func (UnimplementedJsonrpcServer) testEmbeddedByValue()                 {}

// UnsafeJsonrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JsonrpcServer will
// result in compilation errors.
type UnsafeJsonrpcServer interface {
	mustEmbedUnimplementedJsonrpcServer()
}

func RegisterJsonrpcServer(s grpc.ServiceRegistrar, srv JsonrpcServer) {
	// If the following call pancis, it indicates UnimplementedJsonrpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Jsonrpc_ServiceDesc, srv)
}

func _Jsonrpc_GetJsonrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJsonrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JsonrpcServer).GetJsonrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Jsonrpc_GetJsonrpc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JsonrpcServer).GetJsonrpc(ctx, req.(*GetJsonrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Jsonrpc_PostJsonrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostJsonrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JsonrpcServer).PostJsonrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Jsonrpc_PostJsonrpc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JsonrpcServer).PostJsonrpc(ctx, req.(*PostJsonrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Jsonrpc_ServiceDesc is the grpc.ServiceDesc for Jsonrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Jsonrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jsonrpc.v1.Jsonrpc",
	HandlerType: (*JsonrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetJsonrpc",
			Handler:    _Jsonrpc_GetJsonrpc_Handler,
		},
		{
			MethodName: "PostJsonrpc",
			Handler:    _Jsonrpc_PostJsonrpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/jsonrpc/v1/jsonrpc.proto",
}
