apiVersion: v1
kind: Service
metadata:
  name: your-project-server
  namespace: your-project-dev
  labels:
    app.kubernetes.io/name: your-project-server
    app.kubernetes.io/part-of: your-project
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: your-project-server
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9000
      targetPort: grpc
      protocol: TCP
