const { FlatCompat } = require('@eslint/eslintrc')
const js = require('@eslint/js')

const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
})

module.exports = [
  ...compat.config({
    env: {
      browser: true,
      es2021: true,
      node: true,
      commonjs: true,
    },
    extends: ['plugin:react/recommended', 'airbnb'],
    parserOptions: {
      ecmaFeatures: {
        experimentalObjectRestSpread: true,
        jsx: true,
        arrowFunctions: true,
        classes: true,
        modules: true,
        defaultParams: true,
      },
      ecmaVersion: 'latest',
      sourceType: 'module',
      allowImportExportEverywhere: false,
      codeFrame: true,
    },
    plugins: ['react', 'react-hooks', 'tailwindcss'],
    rules: {
      // 个人开发低噪音基线：优先保留会影响稳定性的规则，弱化样式/偏好类规则。
      indent: 0,
      'arrow-body-style': 0,
      'no-plusplus': 0,
      'no-confusing-arrow': 0,
      'no-console': 0,
      'no-const-assign': 2,
      'no-param-reassign': 0,
      'no-shadow': 0,
      'no-return-assign': 0,
      'no-prototype-builtins': 0,
      'no-restricted-syntax': 0,
      'no-restricted-globals': 0,
      'no-use-before-define': 0,
      'no-unused-expressions': 0,
      'no-unused-vars': 0,
      'no-empty': 0,
      'no-nested-ternary': 0,
      'no-continue': 0,
      'no-lonely-if': 0,
      'no-await-in-loop': 0,
      'no-promise-executor-return': 0,
      'no-underscore-dangle': 0,
      'no-multi-assign': 0,
      'object-curly-newline': 0,
      'import/no-unresolved': 0,
      'import/prefer-default-export': 0,
      'import/no-extraneous-dependencies': 0,
      'import/extensions': 0,
      'implicit-arrow-linebreak': 0,
      'function-paren-newline': 0,
      'comma-dangle': 0,
      'consistent-return': 0,
      'jsx-a11y/click-events-have-key-events': 0,
      'jsx-a11y/no-static-element-interactions': 0,
      'max-classes-per-file': 0,
      'operator-linebreak': 0,
      'no-mixed-operators': 0,
      'nonblock-statement-body-position': 0,
      'brace-style': 0,
      'generator-star-spacing': 0,
      'max-len': 0,
      'class-methods-use-this': 0,
      camelcase: 0,
      semi: [2, 'never'],
      'semi-style': 0,
      eqeqeq: 'warn',
      'react/function-component-definition': 0,
      'react/jsx-wrap-multilines': 0,
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 0,
      'react/no-array-index-key': 0,
      'react/button-has-type': 0,
      'react/react-in-jsx-scope': 0,
      'react/jsx-filename-extension': 0,
      'react/jsx-one-expression-per-line': 0,
      'react/jsx-props-no-spreading': 0,
      'react/prop-types': 0,
      'react/jsx-curly-newline': 0,
      'jsx-a11y/label-has-associated-control': 0,
      'jsx-a11y/control-has-associated-label': 0,
      'tailwindcss/classnames-order': 'warn',
      'tailwindcss/no-custom-classname': 'off',
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
  }),
]
