apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-template-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://192.168.0.108:8929/root/webapp-template-lab.git
    targetRevision: main
    path: server/deploy/lab-ha/charts/webapp-template
    helm:
      releaseName: webapp-template-lab
      valueFiles:
        - values-lab.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
